var foodDIY=[
	{id:1,img:'img/foods/diy1.jpg',title:'驴打滚',abstract:'来保定上大学第一年，在街上看到驴打滚，那是第一次吃驴打滚，吃起来软软的，甜甜的，从此只要上街就会买一块驴打滚，满足味蕾的对美食的贪恋。今天去街上看到驴打滚，一秒钟决定要尝试自己做，才有了今天的驴打滚！',content:'<p>1:材料：糯米粉、黄豆面、红豆沙、温水。</p><p>2:糯米粉倒入容器，加入适量温水。</p><p>3:揉成光滑滋腻的面团。</p><p>4:在盘底抹一层香油，将面放在盘中，包上保鲜膜。</p><p>5:上锅蒸，20分钟左右，前5~10分钟大火，后面改小火</p><p>6:黄豆面倒到锅中翻炒，炒成金黄色，并有一点点糊味。（有糊味≠炒成黑色）</p><p>7:待面蒸好取出，包入抹少许油的保鲜膜上擀成片。</p><p>8:切去边角，将红豆沙均匀抹在上面。<p>9:从一头卷成卷。</p><p>10:在最外层均匀的撒上黄豆面。',putDate:'2017-06-05',see:'50',author:'admin',star:'<i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i>'},
	{id:2,img:'img/foods/diy2.jpg',title:'广东的味道——肠粉',abstract:' 关于广式肠粉的起源，目前似乎还没有统一的说法，据说早在清代末期，广州街头上就能听到卖肠粉的叫卖声。也有传说是乾隆皇帝游江南那会儿，被纪晓岚拐骗去粤西吃肠粉，当即赞不绝口，并乘兴说：“这米粉有点像猪肠子”，所以就叫肠粉了。',content:'<p>1.用我们家里平时用的米杯子来配粉浆，一杯粉加1.25杯水（体积比1:1.25/重量比1:2.5）</p><p>2.把粉和水混合在一起，搅拌均匀；</p><p>3.蒸盘中倒入薄薄的一层粉浆，之后可以加入您喜欢吃的馅料；</p><p>4.在锅内倒入适量的水，煮开，将盛有粉浆的铁盘放入锅内隔水蒸；一次制作多碟肠粉可以将铁盘十字型层叠错开：</p><p>5.取出蒸盘，用刮刀卷起装碟，即可调味食用。调味可以用海鲜酱油、蚝油调味，视个人口味。</p><p>6.此食谱由白鲨食品官方原创提供，转载请注明来源，谢谢！</p>',putDate:'2017-06-05',see:'50',author:'admin',star:'<i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i>'},
	{id:3,img:'img/foods/diy3.jpg',title:'鱼茸虾米萝卜糕',abstract:'萝卜糕是款非常广式的点心，通常配方都是米粉，萝卜、腊味之类的配搭，这次配的是鲮鱼肉，做出的萝卜糕也是款美味点心。',content:'<p>1:将在来米粉与500cc的水搅匀成米浆后备用</p><p>2:广式香肠切成小丁状；虾米泡水后切碎成末。我个人不喜欢吃到萝卜糕里面有硬硬的虾米，觉得口感不好。剁碎可以让萝卜糕有虾米香却不会吃到硬梆梆的虾米颗粒。</p><p>3:白萝卜去皮刨丝，加入600cc的水煮滚至软透，加入盐后熄火。然后加入香肠丁和虾米末。</p><p>4:一般我不会煮到萝卜丝全软，这样能够保留一点点硬度。在做好时让萝卜糕还可以吃的到萝卜丝的真材实料搂。</p><p>5:将在来米浆加入熄火后的白萝卜丝锅内，迅速拌匀成萝卜糊状。</p><p>6:将萝卜米浆倒入长条形容器中（可用30cm x 12 cm x 12 cm的磅蛋糕烤盘或是玻璃烤盘）如果想要容易取出可以先抹少许油在容器内，或是使用耐高温（至少要能耐120度C）的保鲜膜。</p><p>7:放入蒸笼中，用大火蒸约四十分钟，或是至萝卜糕中间插入竹签，竹签上不有乳白色的浆即可。</p><p>8:这份食谱可以做约两条萝卜糕。用干净的刀将冷却后的萝卜糕切片。一条冷藏，另一条（也是切好片）用保鲜袋密封后，放冷冻。要吃时随时拿出来用中小火煎一下就可以了。萝卜糕冷冻前一定要先切片，不然你要吃时会发现没有先切片的冷冻萝卜糕会硬到根本切不开</p>',putDate:'2014-01-03',see:'50',author:'admin',star:'<i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i>'},
	{id:4,img:'img/foods/diy4.jpg',title:'喜饼',abstract:'喜饼是山东特色面食之一，它是由面粉、鸡蛋、糖、油等制作而成，因此营养也是相当丰富。第一次做它就给了我一份惊喜，因为没想到这饼会这么好吃。喜饼入口，外皮酥脆里面喧软、嫩滑，还带着浓浓的蛋香、奶香，实在让人欲罢不能，有种吃不够的感觉哈。',content:'<p>1:酵母加温水化开，所有材料加入面粉和成面团，放入温暖处发酵,发酵至两倍大。喜饼的家常做法</p><p>2:把面团分成8个大小一样的剂子,分别排气揉至光滑，再揉圆。喜饼的家常做法</p><p>3:用擀面杖擀成小圆饼，放入烤盘，放在温暖处发酵。喜饼的家常做法</p><p>4:发酵至饼饱满刷一点油，烤箱预热150度，放入发酵好的饼烤至30分钟左右，中间翻面一次。</p>',putDate:'2017-06-05',see:'50',author:'admin',star:'<i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i>'},
	{id:5,img:'img/foods/diy5.jpg',title:'狼牙土豆',abstract:'土豆是我们日常生活中很常见的食材,做法也丰富多彩,大家最为熟悉的应该就是薯条,但身为四川人,不爱薯条独独钟,这狼！牙！土！豆！,从小吃到大,这是街头巷尾都能找到的美味,现炸现卖,又便宜，又美味,被称为"夜市小吃之王",做法简单快捷好吃的秘诀就在酱汁里',content:'<p>1.土豆削皮以后切成厚片，厚度适中即可</p><p>2.用专门的模具切刀把每一片切成条（这种模具刀很常见，淘宝上有卖的，几块钱而已，或者在有些2元店10元店什么的也有卖的，刀很锋利很好用哦）。</p><p>3.用模具刀切出来的样子（旁边放一大碗冷水，切土豆条的时候边切边把切好的放进水里浸泡。原因是因为土豆淀粉含量高，遇空气之后会容易变色）。</p><p>4.切好了一大份之后用冷水把土豆条冲洗2遍后沥水捞起（目的是洗去土豆条表层的淀粉，油炸的时候不容易黏锅）。</p><p>5. 锅烧热后里倒油，将油烧热。<p>6.油烧至7分熟时将沥干水了的土豆条放进去炸（不用太多油，免得浪费，土豆很容易熟的，根据个人口味喜欢吃脆的就少炸一会儿，喜欢吃软烂的就多炸一会儿）</p><p>7.炸好后捞起，放入盐、生抽、醋、蒜泥、辣椒油、辣椒粉、花椒油（粉）葱花、香菜、孜然粉、五香粉拌匀，喜欢吃辣的还可以放小米辣进去哦。</p>',putDate:'2017-06-05',see:'50',author:'admin',star:'<i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i>'},
	{id:6,img:'img/foods/diy6.jpg',title:'牛肉鸡蛋肠粉#樱花味道#',abstract:'肠粉是广东的一道有名的小吃，口感劲道绵软，第一次品尝就被他征服，以至于从广东回来好几年了，家人还一直念念不忘。很偶然得知竟然还有专门的粉，立刻实验了下，操作非常简单，按照说明方法配置好酱汁，蒸熟后淋上酱汁简单拌拌就好了，简单还方便哦。口感相当好呢。',content:'<p>1、食材准备好，牛肉切丝备用</p><p>2、肠粉加水，混合均匀</p><p>3、肠粉专用盘子上刷油，将肠粉水倒进去，薄薄的一层即可</p><p>4、将盘子放在开水上</p><p>5、打入一个鸡蛋，滑散，撒上牛肉丝，再撒上青菜丝，盖上锅盖蒸至凝固即可</p><p>6、用专门的刮刀将肠粉刮下</p><p>7、摆盘</p>',putDate:'2017-06-05',see:'50',author:'admin',star:'<i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i>'}
]

